using System.Collections.Generic;
using System.Data;

namespace Ant0nRocket.Lib.Std20.Data
{
    /// <summary>
    /// Very simple param mapper for <see cref="IDbCommand"/>.
    /// </summary>
    public class SqlParamMapper
    {
        private Dictionary<string, object> _keyValues { get; } = new();

        /// <summary>
        /// Simple SQl-expression text.
        /// </summary>
        public string SqlCommandText { get; private set; }

        /// <summary>
        /// Constructor. Command text should be passed here.
        /// </summary>
        /// <param name="sqlCommandText"></param>
        public SqlParamMapper(string sqlCommandText)
        {
            SqlCommandText = sqlCommandText;
        }

        /// <summary>
        /// Addes a parameter to DbCommand generated by <see cref="CreateDbCommand(IDbConnection)"/>.
        /// </summary>
        public SqlParamMapper AddKeyValue(string key, object value, bool overrideExistingValues = false)
        {
            if (!_keyValues.ContainsKey(key))
            {
                _keyValues.Add(key, value);
            }
            else
            {
                if (overrideExistingValues)
                    _keyValues[key] = value;
            }

            return this;
        }

        /// <summary>
        /// Returnes a DbCommand with parameters added by <see cref="AddKeyValue(string, object, bool)"/>.
        /// </summary>
        public IDbCommand CreateDbCommand(IDbConnection connection)
        {
            var command = connection.CreateCommand();
            command.CommandText = SqlCommandText;

            foreach (var kvp in _keyValues)
            {
                var parameter = command.CreateParameter();
                parameter.ParameterName = kvp.Key;
                parameter.Value = kvp.Value;
                command.Parameters.Add(parameter);
            }

            return command;
        }
    }
}
