<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<LangVersion>latest</LangVersion>
		<Description>Helpfull code: hasing, file-system utils, etc.</Description>
		<PackageProjectUrl>https://github.com/Ant0nRocket/Ant0nRocket.Lib</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Copyright>Ant0nRocket</Copyright>
		<Version>2026.7.29</Version>
		<PackageLicenseExpression>Beerware</PackageLicenseExpression>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<Target Name="PostPackNugetDeploy" AfterTargets="Pack">
		<Exec Command="dotnet nuget push &quot;$(ProjectDir)$(PackageOutputPath)$(PackageId).$(PackageVersion).nupkg&quot; --source Local" />
	</Target>
</Project>